/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_native_JNI */

#ifndef _Included_java_native_JNI
#define _Included_java_native_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_native_JNI
 * Method:    sayHii
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_1native_JNI_sayHii
  (JNIEnv *, jobject);

/*
 * Class:     java_native_JNI
 * Method:    multiply
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_java_1native_JNI_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
